/* 
This is automatically generated file. 
DO NOT EDIT THIS FILE. 

\author		Shun Moriya
\copyright	2023 Shun Moriya
*/

#pragma once 
#define JENKINS_BUILD_NUMBER "0" 
#define JENKINS_BUILD_ID "local build" 
#define JENKINS_GIT_BRANCH "" 
#define JENKINS_GIT_COMMIT "" 
