/**
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya 
\copyright	2023- Shun Moriya 
*/
#pragma once
#define DUNGENERATOR_PLUGIN_FILE_VERSION "3"
#define DUNGENERATOR_PLUGIN_VERSION "1"
#define DUNGENERATOR_PLUGIN_VERSION_NAME "0.1"
#define DUNGENERATOR_PLUGIN_FRIENDLY_NAME "DungeonGenerator"
#define DUNGENERATOR_PLUGIN_DESCRIPTION "Generates a three-dimensional dungeon."
#define DUNGENERATOR_PLUGIN_DOCS_URL "https://github.com/shun126/DungeonGenerator/wiki/"
#define DUNGENERATOR_PLUGIN_SUPPORT_URL "https://github.com/shun126/DungeonGenerator/issues/"
#define DUNGENERATOR_PLUGIN_BETA_VERSION "true"
