/**
 * ダンジョン生成パラメータに関するヘッダーファイル
 *
 * @author		Shun Moriya
 * @copyright	2023- Shun Moriya
 * All Rights Reserved.
 */

#pragma once
#include "Parameter/DungeonLayoutTypes.h"
#include "PathGeneration/StartLocationPolicy.h"
#include <Math/IntVector.h>
#include <memory>

namespace dungeon
{
	class Random;

	/**
	 * Dungeon expansion policy
	 *
	 * ダンジョンの拡張ポリシー
	 * DungeonExpansionPolicyと同じ意味にして下さい
	 */
	enum class ExpansionPolicy : uint8_t
	{
		Flat,				// 平面方向にのみ広がる
		ExpandVertically,   // 垂直方向に広がる
		ExpandAnyDirection, // 制限なく広がる
	};

	/**
	 * 通路の天井高ポリシー
	 * EDungeonAisleCeilingHeightPolicyと同じ意味にして下さい
	 */
	enum class AisleCeilingHeightPolicy : uint8_t
	{
		TwoGrids,
		OneGrid,
		Random,
	};

	/**
	 * デフォルトダンジョン生成パラメータクラス
	 */
	struct GenerateParameter final
	{
	public:
		/**
		 * コンストラクタ
		 */
		GenerateParameter();

		/**
		 * デストラクタ
		 */
		~GenerateParameter() = default;

		/**
		 * ダンジョンの拡張ポリシーを取得します
		 */
		ExpansionPolicy GetExpansionPolicy() const noexcept;

		/**
		 * ダンジョンの拡張ポリシーを設定します
		 */
		void SetExpansionPolicy(const ExpansionPolicy policy) noexcept;

		/**
		 * スタート位置のポリシーを取得します
		 */
		StartLocationPolicy GetStartLocationPolicy() const noexcept;

		/**
		 * スタート位置のポリシーを設定します
		 */
		void SetStartLocationPolicy(const StartLocationPolicy startLocationPolicy) noexcept;

		/**
		 * スタート部屋の数を取得します
		 */
		uint8_t GetStartRoomCount() const noexcept;

		/**
		 * スタート部屋の数を設定します
		 */
		void SetStartRoomCount(const uint8_t count) noexcept;

		/**
		 * 生成する部屋の数の候補
		 * 部屋の初期生成数であり、最終的に生成される部屋の数ではありません。
		 */
		uint8_t GetNumberOfCandidateRooms() const noexcept;
		void SetNumberOfCandidateRooms(const uint8_t count) noexcept;

		/**
		 * 部屋の最小の幅
		 */
		uint32_t GetMinRoomWidth() const noexcept;
		void SetMinRoomWidth(const uint32_t width) noexcept;

		/**
		 * 部屋の最大の幅
		 */
		uint32_t GetMaxRoomWidth() const noexcept;
		void SetMaxRoomWidth(const uint32_t width) noexcept;

		/**
		 * 部屋の最小の奥行き
		 */
		uint32_t GetMinRoomDepth() const noexcept;
		void SetMinRoomDepth(const uint32_t depth) noexcept;

		/**
		 * 部屋の最大の奥行き
		 */
		uint32_t GetMaxRoomDepth() const noexcept;
		void SetMaxRoomDepth(const uint32_t depth) noexcept;

		/**
		 * 部屋の最小の高さ
		 */
		uint32_t GetMinRoomHeight() const noexcept;
		void SetMinRoomHeight(const uint32_t height) noexcept;

		/**
		 * 部屋の最大の高さ
		 */
		uint32_t GetMaxRoomHeight() const noexcept;
		void SetMaxRoomHeight(const uint32_t height) noexcept;

		/**
		 * 部屋と部屋の水平方向の余白
		 */
		uint32_t GetHorizontalRoomMargin() const noexcept;
		void SetHorizontalRoomMargin(const uint32_t margin) noexcept;

		/**
		 * 部屋と部屋の垂直方向の余白
		 */
		uint32_t GetVerticalRoomMargin() const noexcept;
		void SetVerticalRoomMargin(const uint32_t margin) noexcept;

		/**
		 * 乱数発生
		 */
		std::shared_ptr<Random> GetRandom() noexcept;

		/**
		 * 乱数発生
		 */
		std::shared_ptr<Random> GetRandom() const noexcept;




		/**
		 * ダンジョンの幅
		 */
		uint32_t GetWidth() const noexcept;

		/**
		 * ダンジョンの幅
		 */
		void SetWidth(const uint32_t width) noexcept;

		/**
		 * ダンジョンの奥行き
		 */
		uint32_t GetDepth() const noexcept;

		/**
		 * ダンジョンの奥行き
		 */
		void SetDepth(const uint32_t depth) noexcept;

		/**
		 * ダンジョンの高さ
		 */
		uint32_t GetHeight() const noexcept;

		/**
		 * ダンジョンの高さ
		 */
		void SetHeight(const uint32_t height) noexcept;

		bool IsGenerateStartRoomReserved() const noexcept;
		bool IsGenerateGoalRoomReserved() const noexcept;

		bool UseMissionGraph() const noexcept;
		void SetMissionGraph(const bool use) noexcept;

		const FDungeonPathSettings& GetPathSettings() const noexcept;
		void SetPathSettings(const FDungeonPathSettings& settings) noexcept;
		const FDungeonRoomRoleSettings& GetRoomRoleSettings() const noexcept;
		void SetRoomRoleSettings(const FDungeonRoomRoleSettings& settings) noexcept;
		const FDungeonZoneSettings& GetZoneSettings() const noexcept;
		void SetZoneSettings(const FDungeonZoneSettings& settings) noexcept;
		int32 GetLayoutCandidateCount() const noexcept;
		void SetLayoutCandidateCount(const int32 candidateCount) noexcept;

		/*
		 * Gets additional corridor complexity, or 0 while Keys And Locks progression is active.
		 * 追加通路の複雑度を取得します。Keys And Locks進行が有効な間は0を返します。
		 */
		uint8_t GetAisleComplexity() const noexcept;
		void SetAisleComplexity(const uint8_t complexity) noexcept;
		bool IsAisleComplexity() const noexcept;

		AisleCeilingHeightPolicy GetAisleCeilingHeightPolicy() const noexcept;
		void SetAisleCeilingHeightPolicy(const AisleCeilingHeightPolicy policy) noexcept;

		/*
		 * Returns whether indoor slopes may be generated by the internal voxel generator.
		 * 内部ボクセル生成で室内スロープを生成できるかを返します。
		 */
		bool IsGenerateSlopeInRoom() const noexcept;
		void SetGenerateSlopeInRoom(const bool generateSlopeInRoom) noexcept;

		/*
		 * Returns whether structural columns may be generated by the internal voxel generator.
		 * 内部ボクセル生成で構造柱を生成できるかを返します。
		 */
		bool IsGenerateStructuralColumn() const noexcept;
		void SetGenerateStructuralColumn(const bool generateStructuralColumn) noexcept;
		uint8_t GetSkylightChancePercent() const noexcept;
		void SetSkylightChancePercent(const uint8_t skylightChancePercent) noexcept;

		/*
		スタート部屋のサイズ
		*/
		const FIntVector& GetStartRoomSize() const noexcept;

		/*
		スタート部屋のサイズ
		*/
		void SetStartRoomSize(const FIntVector& size) noexcept;

		/*
		ゴール部屋のサイズ
		*/
		const FIntVector& GetGoalRoomSize() const noexcept;

		/*
		ゴール部屋のサイズ
		*/
		void SetGoalRoomSize(const FIntVector& size) noexcept;

	private:
		/**
		 * ダンジョンの幅
		 */
		uint32_t mWidth = 0;

		/**
		 * ダンジョンの奥行き
		 */
		uint32_t mDepth = 0;

		/**
		 * ダンジョンの高さ
		 */
		uint32_t mHeight = 0;

		ExpansionPolicy mDungeonExpansionPolicy = ExpansionPolicy::ExpandAnyDirection;
		StartLocationPolicy mStartLocationPolicy = StartLocationPolicy::UseSouthernMost;
		uint8_t mStartRoomCount = 1;

		/**
		 * 生成する部屋の数の候補
		 * 部屋の初期生成数であり、最終的に生成される部屋の数ではありません。
		 */
		uint8_t mNumberOfCandidateRooms = 1;

		/*
		 * Compatibility flag mirrored from ProgressionPolicy == KeysAndLocks.
		 * ProgressionPolicy == KeysAndLocksから同期される互換フラグです。
		 */
		bool mUseMissionGraph = true;

		/**
		 * Layout profile settings used by the intent-driven generator.
		 *
		 * 意図グラフ型ジェネレーターで使うレイアウトプロファイル設定です。
		 */
		FDungeonPathSettings mPathSettings;
		FDungeonRoomRoleSettings mRoomRoleSettings;
		FDungeonZoneSettings mZoneSettings;

		/**
		 * Number of layout candidates evaluated before committing a dungeon.
		 *
		 * ダンジョン確定前に評価するレイアウト候補数です。
		 */
		int32 mLayoutCandidateCount = 3;

		/*
		 * Additional corridor complexity before progression-specific filtering.
		 * 進行方針によるフィルタ前の追加通路複雑度です。
		 */
		uint8_t mAisleComplexity = 0;

		AisleCeilingHeightPolicy mAisleCeilingHeightPolicy = AisleCeilingHeightPolicy::Random;

		/*
		 * Internal option currently set by DungeonGenerateBase during parameter transfer.
		 * 現在はDungeonGenerateBaseからのパラメータ転送時に設定される内部オプションです。
		 */
		bool mGenerateSlopeInRoom = true;

		/*
		 * Internal option currently set by DungeonGenerateBase during parameter transfer.
		 * 現在はDungeonGenerateBaseからのパラメータ転送時に設定される内部オプションです。
		 */
		bool mGenerateStructuralColumn = true;

		/*
		 * Internal skylight chance currently set by DungeonGenerateBase during parameter transfer.
		 * 現在はDungeonGenerateBaseからのパラメータ転送時に設定される内部の天窓生成率です。
		 */
		uint8_t mSkylightChancePercent = 8;

		/**
		 * 部屋の最小の幅
		 */
		uint32_t mMinRoomWidth = 0;

		/**
		 * 部屋の最大の幅
		 */
		uint32_t mMaxRoomWidth = 0;

		/**
		 * 部屋の最小の奥行き
		 */
		uint32_t mMinRoomDepth = 0;

		/**
		 * 部屋の最大の奥行き
		 */
		uint32_t mMaxRoomDepth = 0;

		/**
		 * 部屋の最小の高さ
		 */
		uint32_t mMinRoomHeight = 0;

		/**
		 * 部屋の最大の高さ
		 */
		uint32_t mMaxRoomHeight = 0;

		/**
		 * 部屋と部屋の水平方向の余白
		 */
		uint32_t mHorizontalRoomMargin = 0;

		/**
		 * 部屋と部屋の垂直方向の余白
		 */
		uint32_t mVerticalRoomMargin = 0;

		/**
		 * 乱数生成器
		 */
		std::shared_ptr<Random> mRandom;

		/**
		 * スタート部屋のサイズ
		 */
		FIntVector mStartRoomSize = { 0, 0, 0 };

		/**
		 * ゴール部屋のサイズ
		 */
		FIntVector mGoalRoomSize = { 0, 0, 0 };
	};
}

#include "GenerateParameter.inl"
