/**
 * @author      Shun Moriya
 * @copyright   2026- Shun Moriya
 * All Rights Reserved.
 */

#pragma once
#include <CoreMinimal.h>
#include "DungeonGeneratedRoomInfo.generated.h"

/**
 * Information about a generated room exposed to room sensor Blueprints.
 * 生成された部屋について、ルームセンサーBlueprintへ公開する情報です。
 */
USTRUCT(BlueprintType)
struct DUNGEONGENERATOR_API FDungeonGeneratedRoomInfo
{
	GENERATED_BODY()

	/**
	 * Unique identifier assigned to this generated room.
	 * この生成済み部屋に割り当てられた一意の識別子です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Stable identifier assigned to this generated room."))
	int32 Identifier = 0;

	/**
	 * Structural role assigned to this room.
	 * この部屋が経路上で持つ構造的な役割です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Structural route role of this room, such as Start, Goal, Branch, Hub, or Dead End."))
	EDungeonRoomStructuralRole RoomStructuralRole = EDungeonRoomStructuralRole::Connector;

	/**
	 * Gameplay role assigned to this room.
	 * この部屋でプレイヤーに体験させる遊びの役割です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Gameplay role of this room, such as Combat, Treasure, Puzzle, Rest, or Secret."))
	EDungeonRoomGameplayRole RoomGameplayRole = EDungeonRoomGameplayRole::None;

	/**
	 * Room part category used by legacy room logic.
	 * 旧来の部屋ロジックで使用する部屋パーツ分類です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Generated geometric room-parts classification."))
	EDungeonRoomParts Parts = EDungeonRoomParts::Hall;

	/**
	 * Mission item assigned to this room.
	 * この部屋に割り当てられたミッションアイテムです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Mission item assigned to this room, such as a key or goal item."))
	EDungeonRoomItem Item = EDungeonRoomItem::Empty;

	/**
	 * True when this room is a secret room.
	 * この部屋が隠し部屋の場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Whether this room is assigned the Secret gameplay role."))
	bool bSecretRoom = false;

	/**
	 * True when this room is a dead-end room.
	 * この部屋が行き止まり部屋の場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Whether this room has only one route connection, excluding start and goal rooms."))
	bool bDeadEndRoom = false;

	/**
	 * True when this room belongs to the main route.
	 * この部屋が主経路に属する場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Whether this room belongs to the selected main route."))
	bool bMainPathRoom = false;

	/**
	 * True when this room touches a locked route.
	 * この部屋が鍵付き経路に接続している場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Whether this room belongs to a route protected by a mission lock."))
	bool bLockedRouteRoom = false;

	/**
	 * True when this room has at least one locked door actor.
	 * この部屋に鍵付きドアアクターがある場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Whether an aisle connected to this room contains a locked door."))
	bool bHasLockedDoor = false;

	/**
	 * Branch identifier generated by the mission graph.
	 * Mission Graph によって生成された分岐識別子です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Identifier of the route branch containing this room."))
	uint8 BranchId = 0;

	/**
	 * Room depth from the start room.
	 * スタート部屋からの部屋深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Room depth from the start room."))
	uint8 DepthFromStart = 0;

	/**
	 * Deepest room depth measured from the start room.
	 * スタート部屋から最も深い部屋までの深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Deepest room depth measured from the start room."))
	uint8 DeepestDepthFromStart = 0;

	/**
	 * Normalized room depth from start to deepest room.
	 * スタートから最深部屋までで正規化した部屋深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Normalized progress from the start room, in the range 0 to 1."))
	float DepthFromStartRatio = 0.f;

	/**
	 * Zone display name assigned to this room.
	 * この部屋に割り当てられたゾーン表示名です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Display name of the zone selected for this room, or None when no zone matches."))
	FName ZoneName;

	/**
	 * Zone index assigned to this room, or INDEX_NONE when no zone matched.
	 * この部屋に割り当てられたゾーン番号です。一致するゾーンがない場合はINDEX_NONEです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room", meta = (ToolTip = "Zero-based index of the zone selected for this room, or INDEX_NONE when no zone matches."))
	int32 ZoneIndex = INDEX_NONE;

};
