/**
 * @author		Shun Moriya
 * @copyright	2026- Shun Moriya
 * All Rights Reserved.
 */

#pragma once
#include <CoreMinimal.h>
#include "DungeonGeneratedRoomInfo.generated.h"

/**
 * Information about a generated room exposed to room sensor Blueprints.
 * 生成された部屋について、ルームセンサーBlueprintへ公開する情報です。
 */
USTRUCT(BlueprintType)
struct DUNGEONGENERATOR_API FDungeonGeneratedRoomInfo
{
	GENERATED_BODY()

	/*
	 * Unique identifier assigned to this generated room.
	 * この生成済み部屋に割り当てられた一意の識別子です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	int32 Identifier = 0;

	/**
	 * Structural role assigned to this room.
	 * この部屋が経路上で持つ構造的な役割です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	EDungeonRoomStructuralRole RoomStructuralRole = EDungeonRoomStructuralRole::Connector;

	/**
	 * Gameplay role assigned to this room.
	 * この部屋でプレイヤーに体験させる遊びの役割です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	EDungeonRoomGameplayRole RoomGameplayRole = EDungeonRoomGameplayRole::None;

	/**
	 * Room part category used by legacy room logic.
	 * 旧来の部屋ロジックで使用する部屋パーツ分類です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	EDungeonRoomParts Parts = EDungeonRoomParts::Hall;

	/**
	 * Mission item assigned to this room.
	 * この部屋に割り当てられたミッションアイテムです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	EDungeonRoomItem Item = EDungeonRoomItem::Empty;

	/**
	 * True when this room is a secret room.
	 * この部屋が隠し部屋の場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	bool bSecretRoom = false;

	/**
	 * True when this room is a dead-end room.
	 * この部屋が行き止まり部屋の場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	bool bDeadEndRoom = false;

	/**
	 * True when this room belongs to the main route.
	 * この部屋が主経路に属する場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	bool bMainPathRoom = false;

	/**
	 * True when this room touches a locked route.
	 * この部屋が鍵付き経路に接続している場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	bool bLockedRouteRoom = false;

	/**
	 * True when this room has at least one locked door actor.
	 * この部屋に鍵付きドアアクターがある場合はtrueです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	bool bHasLockedDoor = false;

	/*
	 * Branch identifier generated by the mission graph.
	 * Mission Graph によって生成された分岐識別子です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	uint8 BranchId = 0;

	/**
	 * Room depth from the start room.
	 * スタート部屋からの部屋深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	uint8 DepthFromStart = 0;

	/*
	 * Deepest room depth measured from the start room.
	 * スタート部屋から最も深い部屋までの深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	uint8 DeepestDepthFromStart = 0;

	/**
	 * Normalized room depth from start to deepest room.
	 * スタートから最深部屋までで正規化した部屋深度です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	float DepthFromStartRatio = 0.f;

	/**
	 * Zone display name assigned to this room.
	 * この部屋に割り当てられたゾーン表示名です。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	FName ZoneName;

	/**
	 * Zone index assigned to this room, or INDEX_NONE when no zone matched.
	 * この部屋に割り当てられたゾーン番号です。一致するゾーンがない場合はINDEX_NONEです。
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DungeonGenerator|Room")
	int32 ZoneIndex = INDEX_NONE;
};
