/**
@author		Shun Moriya
@copyright	2024- Shun Moriya
All Rights Reserved.
*/

#pragma once
#include "DungeonGenerateBase.h"
#include "DungeonGeneratedActor.generated.h"

/**
 * Dungeon-generated actors.
 * Actors generated by the generator to hold the InstancedStaticMeshComponent, etc. when generated in the editor.
 *
 * ダンジョン生成済みアクター
 * エディタ内で生成した時にInstancedStaticMeshComponent等を保持するためジェネレーターが生成するアクター
 */
UCLASS(NotPlaceable)
class DUNGEONGENERATOR_API ADungeonGeneratedActor : public ADungeonGenerateBase
{
	GENERATED_BODY()

public:
	/**
	 * constructor
	 * コンストラクタ
	 */
	explicit ADungeonGeneratedActor(const FObjectInitializer& initializer);

	/**
	 * destructor
	 * デストラクタ
	 */
	virtual ~ADungeonGeneratedActor() override = default;

	/**
	 * Generate new dungeon
	 * ダンジョンを生成します
	 * @param[in]	parameter		UDungeonGenerateParameter
	 * @return		If false, generation fails
	 */
	bool Generate(const UDungeonGenerateParameter* parameter);

private:
	static ADungeonGeneratedActor* SpawnDungeonActor(UWorld* world, const FVector& location);

	// friend class
	friend class FDungeonGenerateEditorModule;
};
